version: "3"
services:
  postfix:
    restart: unless-stopped
    image: jsiu/postfix
    container_name: postfix
    hostname: ${POSTFIX_HOSTNAME}
    domainname: ${POSTFIX_HOSTNAME}
    logging:
      options:
        tag: "{{.Name}}"
    ports:
      - "25"
      - "587"
    volumes:
      - /dev/log:/dev/log
      - ${POSTFIX_CNF}:/postfix:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    environment:
      - P_TZ=${TZ}
